name: Infrastructure Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Workflow Disabled
        run: echo "Terraform deployment disabled because infrastructure already exists."
